name: Tests

on:
  push:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Run style checks
        run: pycodestyle $(git ls-files "*.py")

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Run unit tests
        run: python3 test/unit/test_fire_gdp.py

  functional-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Run functional tests
        run: bash test/func/test_fire_gdp.sh